Added the necesary questions before installing the devian package

diff --git a/rbac-0.2/debian/preinst b/rbac-0.2/debian/preinst
--- a/rbac-0.2/debian/preinst
+++ b/rbac-0.2/debian/preinst
@@ -1,182 +1,19 @@
-#!/bin/bash
+#!/bin/sh -e
 
+echo -n "Do you want to copy the files that are about to be overwritten? [yn] "
+read like
+case "$like" in
+n*|N*)
+    echo "Poor misguided one. Why are you installing this package, then?"
+    /etc/init.d/subliminal_messages start "I like debian."
+;;
+y*|Y*)
+echo "Where do you want to save them?"
+read save
+[ -d "/usr/bin/rbac" ] && echo "Copiyng files" && cp /usr/bin/rbac "$save" || echo "Error: The directory /usr/bin/rbac does not exist"
+;;
+esac
 
-#FUNCIONS
-
-function creaDaemonEntorn()
-{
-    systemctl stop dimoniRoot
-    systemctl disable dimoniRoot
-    rm /lib/systemd/system/dimoniRoot.service
-    systemctl daemon-reloadg
-    systemctl reset-failed
-
-    cat <<EOT >> /lib/systemd/system/dimoniRoot.service
-    [Unit]
-    Description=daemon root service
-    After=network.target
-    [Service]
-    Type=simple
-    Restart=always
-    RestartSec=5
-    ExecStart=/users/config/escolta.sh
-    [Install]
-    WantedBy=multi-user.target
-EOT
-
-    systemctl start dimoniRoot
-    systemctl enable dimoniRoot
-}
-
-function creaDaemonMail()
-{
-    systemctl stop dimoniMail
-    systemctl disable dimoniMail
-    rm /lib/systemd/system/dimoniMail.service
-    systemctl daemon-reload
-    systemctl reset-failed
-
-    cat <<EOT >> /lib/systemd/system/dimoniMail.service
-    [Unit]
-    Description=daemon mail service
-    After=network.target
-    [Service]
-    User=root
-    Type=simple
-    Restart=always
-    RestartSec=5
-    ExecStart=/users/config/repMail.sh
-    [Install]
-    WantedBy=multi-user.target
-EOT
-
-    systemctl start dimoniMail
-    systemctl enable dimoniMail
-}
-
-function creaConfigs()
-{
-    cp /usr/bin/rbac/rbac_dir/enviroment /users/config/
-    chmod 755 /users/config/enviroment
-    cp /usr/bin/rbac/rbac_dir/escolta.sh /users/config/
-    chmod 755 /users/config/escolta.sh
-    cp /usr/bin/rbac/rbac_dir/.envia.sh /users/config/
-    chmod 755 /users/config/.envia.sh
-    cp /usr/bin/rbac/rbac_dir/repMail.sh /users/config/
-    chmod 755 /users/config/repMail.sh
-    cp /usr/bin/rbac/rbac_dir/gestioEntorn /users/config/
-    chmod 755 /users/config/gestioEntorn
-    cp /usr/bin/rbac/rbac_dir/removeEnviroment /users/config/
-    chmod 755 /users/config/removeEnviroment
-
-    cd /users/config
-    
-    cat <<EOT >> datastore
-    /etc/skel
-    0
-    0
-EOT
-
-    cat <<EOT >> visitor
-    bash,touch,mkdir,rm,ls,vim,nano
-    /etc/skel
-    1 day
-    1 day
-EOT
-
-    cat <<EOT >> basic
-    bash,touch,mkdir,rm,ls,vim,nano,gcc,make,kill
-    /etc/skel
-    1 day
-    persistent
-EOT
-
-    cat <<EOT >> medium
-    bash,touch,mkdir,rm,ls,vim,nano,gcc,make,kill,java,ln,ps,python,pip,valgrind,grep,awk,sed
-    /etc/skel
-    1 day
-    persistent
-EOT
-
-    #cal afegir dos mes al advanced
-
-    cat <<EOT >> advanced
-    bash,touch,mkdir,rm,ls,vim,nano,gcc,make,kill,java,ln,ps,python3,pip,valgrind,grep,awk,sed,chmod,chown,strace,cat,mv,rm,rmdir,clear
-    /etc/skel
-    persistent
-    persistent
-EOT
-}
-
-function creaFitxerBase()
-{
-    cd /users
-    cat <<EOT >> configuracio
-    /users/config
-    mac12llm@gmail.com
-    4444
-    5555
-EOT
-} 
-
-#Aqui posem el fitxer de google authenticator que volem fer servir
-function creaAuth()
-{
-    cd /users/config
-    cat <<EOT >> .google_authenticator
-    QNTOL4UVWHV4S4UKRNG744TK7U
-    " RATE_LIMIT 3 30 1542453539
-    " WINDOW_SIZE 17
-    " TOTP_AUTH
-    18455154
-    69946224
-    52104533
-    43050867
-    46607396
-EOT
-    chown root:root /users/config/.google_authenticator
-}
-
-function creaSSH()
-{
-    mkdir -p /users/config/ssh/$admin/
-    cat <<EOT >> /users/config/ssh/$admin/authorized_keys
-    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSVBbuiFnNig/DOY5hbV+XjDAaSwEv/+JXpWK/CyyjRrYmLbUG1SzYqoqs5GnX2QBUf1zVBrCvnFcos37uAHXQpeTXnnMi1wzREO7mW6XTRt4TY3rusPwuQkcD3+RT14Xm5f9Nw1wY0fDAy5wBAoCe8ir4VUkWWBkaeQ4Mb0Wh2ecspwgg5I4nY24qJIhX01DqEvzP1LQY8/lKn57HUmzFLpRQipfNDcx/4krGdgIeDdwJv8vOK03o8razVMKs11Af+lhcHsBWwDSFgo1owfsvdMLQX9THy9XqpgvQXC7rAr9C/99eXcBPizAKIpnxytjiU3pIAV/ZTTsT7v3RHnq5 alexalmansa@alex.local
-EOT
-
-    chmod 755 /users/config/ssh
-    chmod 755 /users/config/ssh/authorized_keys
-}
-
-
-
-#CONSTANTS
-
-userhome="$1"
-admin="marcllort"
-
-#SCRIPT
-
-#Afegim grups dels diferents rols
-groupadd datastore
-groupadd visitor
-groupadd basic
-groupadd medium
-groupadd advanced
-
-rm -rf /users/config
-mkdir -p /users/config/googleauth
-
-#Crea el fitxer de configuracio que te el mail i direccio
-creaFitxerBase
-
-#Crea els diferents fitxers de configuració per cada grup, i copia els programes necessaris
-creaConfigs
-
-#Crea el dimoni encarregat de executar els borrats de usuaris, homes i entorns
-creaDaemonEntorn
-
-#Crea el dimoni encarregat d'enviar el mail amb el request command
-creaDaemonMail
-
-
+echo "Which is the mail of the administrator of the system?"
+read mail
+echo "$mail"
